import test from 'node:test';
import assert from 'node:assert/strict';
import { planReconciliationV2 } from '../dist/reconcileV2.js';
import { classifyAppointmentV2 } from '../dist/serviceRulesV2.js';
import { reliableSupabaseRequest, AtomicSupabaseRepository } from '../dist/reliableSupabase.js';
import { processLifecycleMessageV2 } from '../dist/workerV2.js';

const oldToken = '11111111-1111-4111-8111-111111111111';
const newToken = '22222222-2222-4222-8222-222222222222';
const service = { serviceName: 'Ladies’ Curly Haircut & Styling', staffName: 'Stylist A', serviceTime: '3:00PM' };
const snapshot = { id: 'a', timelyBookingId: 'BG123', timelyChangeToken: oldToken, email: 'client@example.com', mobile: '+6591112222', appointmentLocalIso: '2026-09-15T15:00:00+08:00', locationName: 'Hera Hair Beauty @Tanglin Mall', serviceNames: [service.serviceName], serviceDetails: [service], status: 'CONFIRMED' };
function event(overrides = {}) { return { parserVersion: 'TIMELY_EMAIL_V2', eventType: 'CHANGED', subject: 'Appointment changed', customer: { name: 'Test Client', email: 'client@example.com', mobile: '+6591112222' }, appointment: { localIso: snapshot.appointmentLocalIso, displayText: 'Tue, 15 Sep 2026', locationName: snapshot.locationName, services: [service] }, source: { timelyBookingId: 'BG123', timelyChangeToken: newToken, emailFormat: 'CUSTOMER_NOTIFICATION', bookingOrigin: 'UNKNOWN' }, warnings: [], ...overrides }; }
for (const name of ['Keratin Smoothening Treatment (Short)', 'Keratin Smoothening Treatment (Medium)', 'Keratin Smoothening Treatment (Long)', 'Nano Keratin Smoothening Treatment (Short)', 'Nano Keratin Smoothening Treatment (Long)']) {
  test(`unclassified smoothing routes to review: ${name}`, () => { const r = classifyAppointmentV2([name]); assert.equal(r.classifications[0].category, 'MANUAL_REVIEW'); assert.equal(r.preconsultRequired, false); });
}
test('approved exact exclusion remains excluded', () => assert.equal(classifyAppointmentV2(['ROOT Colour+Wash & Styling (Medium)']).classifications[0].category, 'EXCLUDED'));
test('unknown add-on cannot suppress qualifying highlights', () => assert.equal(classifyAppointmentV2(['Partial Highlights', 'Toner (Long)', 'Keratin Smoothening Treatment (Medium)']).preconsultRequired, true));
test('explicit supplied policy wins over unknown-family safeguard', () => assert.equal(classifyAppointmentV2(['Keratin Smoothening Treatment (Medium)'], [{ id: 'approved', category: 'EXCLUDED', priority: 9000, preconsultRequired: false, exactNames: ['Keratin Smoothening Treatment (Medium)'] }]).classifications[0].category, 'EXCLUDED'));
test('same UID permits otherwise unowned token rotation', () => { const p = planReconciliationV2(event(), [snapshot]); assert.equal(p.action, 'UPDATE'); assert.equal(p.bookingId, 'a'); });
test('UID/token resolving to different owners is blocked', () => assert.equal(planReconciliationV2(event(), [snapshot, { ...snapshot, id: 'b', timelyBookingId: 'BG456', timelyChangeToken: newToken }]).action, 'NEEDS_REVIEW'));
test('existing token cannot be reassigned to new UID', () => assert.match(planReconciliationV2(event({ source: { timelyBookingId: 'BG456', timelyChangeToken: oldToken } }), [snapshot]).reason, /^IDENTIFIER_CONFLICT/));
test('historical token alias resolves to original booking', () => { const p = planReconciliationV2(event({ source: { timelyChangeToken: oldToken } }), [{ ...snapshot, timelyChangeToken: newToken, identityAliases: [{ identifierType: 'change_token', identifierValue: oldToken }] }]); assert.equal(p.bookingId, 'a'); assert.equal(p.action, 'UPDATE'); });
test('new UID and token creates distinct rebooking, not resurrection', () => { const p = planReconciliationV2(event({ eventType: 'CONFIRMED', source: { timelyBookingId: 'BG456', timelyChangeToken: newToken } }), [{ ...snapshot, status: 'CANCELLED' }]); assert.equal(p.action, 'CREATE'); });
test('same cancelled UID is never resurrected', () => assert.match(planReconciliationV2(event(), [{ ...snapshot, status: 'CANCELLED' }]).reason, /^CANCELLED_BOOKING_RESURRECTION_BLOCKED/));
test('identifier-less cancellation needs complete service and stylist match', () => { const e = event({ eventType: 'CANCELLED', source: {} }); assert.equal(planReconciliationV2(e, [snapshot]).action, 'CANCEL'); assert.equal(planReconciliationV2(e, [{ ...snapshot, serviceDetails: [{ ...service, staffName: 'Other Stylist' }] }]).action, 'NEEDS_REVIEW'); });
test('confirmed stylist change applies instead of no-op', () => assert.equal(planReconciliationV2(event({ eventType: 'CONFIRMED', appointment: { ...event().appointment, services: [{ ...service, staffName: 'Other Stylist' }] } }), [snapshot]).action, 'UPDATE'));
test('ambiguous same-name clients without contact cannot be matched', () => assert.equal(planReconciliationV2(event({ eventType: 'CANCELLED', source: {}, customer: { name: 'Test Client' } }), [snapshot]).action, 'NEEDS_REVIEW'));

const config = { url: 'https://test.invalid', secretKey: 'sb_secret_test_only' };
test('504 retry is bounded and recovers a safe read', async () => { const original = globalThis.fetch; let count = 0; globalThis.fetch = async () => ++count === 1 ? new Response('{"message":"Gateway Timeout"}', { status: 504 }) : new Response('[]'); try { assert.deepEqual(await reliableSupabaseRequest(config, 'sync_state'), []); assert.equal(count, 2); } finally { globalThis.fetch = original; } });
test('identity conflict is never transport-retried', async () => { const original = globalThis.fetch; let count = 0; globalThis.fetch = async () => { count++; return new Response('{"message":"IDENTIFIER_CONFLICT:owner"}', { status: 400 }); }; try { await assert.rejects(reliableSupabaseRequest(config, 'rpc/test', { method: 'POST', body: '{}' }), /^Error: IDENTIFIER_CONFLICT/); assert.equal(count, 1); } finally { globalThis.fetch = original; } });
test('401 credentials failure is not blindly retried', async () => { const original = globalThis.fetch; let count = 0; globalThis.fetch = async () => { count++; return new Response('{}', { status: 401 }); }; try { await assert.rejects(reliableSupabaseRequest(config, 'sync_state')); assert.equal(count, 1); } finally { globalThis.fetch = original; } });
test('atomic apply uses one RPC and no extra terminal PATCH', async () => { const original = globalThis.fetch; const calls = []; globalThis.fetch = async (url, init) => { calls.push({ url: String(url), body: JSON.parse(init.body) }); return new Response('{"bookingId":"a","outcome":"applied"}'); }; try { const r = new AtomicSupabaseRepository(config); await r.applyPlan({ message: { id: 'm', receivedAt: '2026-09-12T00:00:00Z' }, event: event(), plan: { action: 'UPDATE', bookingId: 'a', reason: 'test' }, classifications: [], timing: 'UPCOMING' }); await r.finishEvent({ gmailMessageId: 'm', bookingId: 'a', parseStatus: 'parsed' }); assert.equal(calls.length, 1); assert.ok(calls[0].url.endsWith('/rpc/hera_apply_lifecycle_v2')); } finally { globalThis.fetch = original; } });
test('terminal event state uses workflow-aware SQL check', async () => { const original = globalThis.fetch; globalThis.fetch = async (url) => { assert.ok(String(url).endsWith('/rpc/hera_event_state_v2')); return new Response('{"exists":true,"processed":false}'); }; try { assert.deepEqual(await new AtomicSupabaseRepository(config).getEventState('m'), { exists: true, processed: false }); } finally { globalThis.fetch = original; } });

function message(kind = 'confirmed', services = ['Keratin Smoothening Treatment (Medium) with Stylist A at 3:00PM'], withIdentity = false) {
  const source = { id: 'test-message', subject: `Your appointment booking has been ${kind}`, receivedAt: '2026-09-12T00:00:00Z', body: [`Appointment ${kind}`, 'Hera Hair Beauty', 'Tue, 15 Sep 2026', ...services, 'At this location', snapshot.locationName, 'Your details', 'Test Client', 'client@example.com', 'Mobile: +6591112222', ...(withIdentity ? [`https://book.gettimely.com/booking/change/${oldToken}`] : [])].join('\n') };
  if (withIdentity) source.calendarAttachments = [`BEGIN:VCALENDAR\r\nBEGIN:VEVENT\r\nUID:BG123\r\nDESCRIPTION:https://book.gettimely.com/booking/change/${oldToken}\r\nEND:VEVENT\r\nEND:VCALENDAR`];
  return source;
}
function repository(candidates = []) { return { alerts: [], finishes: [], plans: [], holds: [], async getEventState() { return { exists: false, processed: false }; }, async startEvent() {}, async listCandidateBookings() { return candidates; }, async applyPlan(input) { this.plans.push(input.plan); return { bookingId: 'a', outcome: 'applied' }; }, async finishEvent(input) { this.finishes.push(input); }, async createAlert(input) { this.alerts.push(input); }, async holdCancellationForReview(e, id) { this.holds.push(id); } }; }
test('worker routes unknown smoothening to review, not ignored', async () => { const r = repository(); const result = await processLifecycleMessageV2(message(), r, new Date('2026-09-12T01:00:00Z')); assert.equal(result.status, 'MANUAL_REVIEW'); assert.equal(r.plans.length, 0); });
test('unknown toner does not block a verified cancellation', async () => { const r = repository([snapshot]); await processLifecycleMessageV2(message('cancelled', ['Toner (Long) with Stylist A at 3:00PM'], true), r, new Date('2026-09-12T01:00:00Z')); assert.equal(r.plans[0].action, 'CANCEL'); });
test('ambiguous cancellation is contact-held, not guessed', async () => { const r = repository([snapshot]); const result = await processLifecycleMessageV2(message('cancelled', ['Ladies’ Curly Haircut & Styling with Stylist A at 3:00PM', 'Toner (Long) with Stylist A at 4:00PM']), r, new Date('2026-09-12T01:00:00Z')); assert.equal(result.status, 'MANUAL_REVIEW'); assert.equal(r.holds.length, 1); assert.equal(r.plans.length, 0); });
test('database staging error is not incorrectly labelled a parser failure', async () => { const r = repository(); r.startEvent = async () => { throw new Error('SUPABASE_REST_504'); }; await assert.rejects(processLifecycleMessageV2(message(), r), /SUPABASE_REST_504/); assert.equal(r.alerts.length, 0); });
test('completed messages are deduplicated without writes', async () => { const r = repository(); r.getEventState = async () => ({ exists: true, processed: true }); const result = await processLifecycleMessageV2(message(), r); assert.equal(result.status, 'DUPLICATE'); assert.equal(r.plans.length, 0); assert.equal(r.finishes.length, 0); });
